# Generated by Django 4.0.2 on 2022-03-26 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='body',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='publication',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='publication',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
