# Generated by Django 4.0.2 on 2022-03-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_diary', '0002_rename_body_publication_summary_publication_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='title_tag',
            field=models.CharField(default='training', max_length=255),
        ),
    ]
