# Generated by Django 4.0.3 on 2022-03-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_diary', '0004_category_publication_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='title_tag',
        ),
    ]
