# Generated by Django 4.0.3 on 2022-03-27 19:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_diary', '0006_alter_category_options_publication_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
