# Generated by Django 4.0.3 on 2022-03-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_diary', '0007_alter_publication_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
