# Generated by Django 4.0.3 on 2022-03-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_diary', '0008_publication_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='header_image',
            new_name='add_image',
        ),
    ]
