# Generated by Django 4.0.3 on 2022-03-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_diary', '0011_userprofile_facebook_url_userprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='static/the_diary/images/profile.png', null=True, upload_to='images/profiles/'),
        ),
    ]
