# Generated by Django 4.0.3 on 2022-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_diary', '0012_alter_userprofile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='images/profiles/'),
        ),
    ]
