# Generated by Django 4.0.3 on 2022-03-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_diary', '0013_alter_userprofile_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_img',
        ),
    ]
